### ISSUE TITLE
RD organization

### ISSUE THREAD

**Issue by hashedone** [ethanboxx/planters-rdconf-hackathon-project#50]
Hi, I am org of Rusty Days conf. Please double check your mailbox (including spam).

**Comment by eopb** [comment]
Hi, @hashedone we got your email on `Wed, 5 Aug` about voting but did not vote in time.

Would commenting our votes here now help? I am trying to get votes from my team now.

**Comment by eopb** [comment]
Just saw the tweet https://twitter.com/rdconf/status/1292560016730394625?s=20 We will have votes for this new deadline. Sorry for the inconvenience.
